[book]
authors = ["Yi-sir"]
language = "zh"
multilingual = false
src = "src"
title = "SM9 User Guide"

[params]
image_dir = "pics"

[output.html]
mathjax-support = true
no-section-label = true
git-repository-url = "https://github.com/Yi-sir/SM9-Develop-User-Guide"
git-repository-icon = "fa-github"

[output.html.fold]
enable = true
level = 1

[output.html.search]
enable = true